import{S as P,a as M,i as b}from"./assets/vendor-da186403.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function c(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=c(t);fetch(t.href,r)}})();document.addEventListener("DOMContentLoaded",function(){const m=document.querySelector(".search-form"),i=document.querySelector(".gallery"),c=document.querySelector(".search-btn"),a=document.querySelector(".loader"),t="gallery-link",r=document.querySelector(".load-more-btn");c.disabled=!0;let s=1,l=null,d=0;const y=new P(`.${t}`,{captionsData:"alt",captionDelay:250});m.elements.query.addEventListener("input",function(){l=this.value.trim(),c.disabled=l===""}),m.addEventListener("submit",async function(e){if(e.preventDefault(),l=e.target.elements.query.value.trim(),l!==""){m.reset(),s=1,i.innerHTML="";try{const{data:o}=await L(l,1);d=o.totalHits,a.style.display="none",E(o.hits),c.disabled=!0;const n=Math.ceil(d/15);w(n),y.refresh(),y.on("show.simplelightbox")}catch(o){console.error("Error fetching images:",o),a.style.display="none",S(`Error fetching images: ${o}`),c.disabled=!1}finally{e.target.elements.query.value=""}}});async function L(e,o=1,n){const g="https://pixabay.com/api/",u=new URLSearchParams({key:"42137546-386b5be41212ccd429cab5a80",q:e,image_type:"photo",orientation:"horizontal",safeSearch:!0,per_page:15,page:o}),f=`?${u}`,h=g+f;try{const p=await M.get(h,{params:{...u}});if(!p.data)throw new Error("No data returned from the API");return{data:p.data,maxPage:n,page:o}}catch(p){throw new Error(`Error fetching images: ${p.message}`)}}function w(e){d===0||s>=e?(r.style.display="none",b.show({message:"We're sorry, but you've reached the end of search results.",color:"red",position:"topRight"})):r.style.display="block"}r.addEventListener("click",v);function q({webformatURL:e,largeImageURL:o,tags:n,likes:g,views:u,comments:f,downloads:h}){return`
  <a href="${o}" class="${t} id="gallery-link">
     <figure>
      <img src="${e}" alt="${n}" class="gallery-image">
      <figcaption class="gallery__figcaption">
        <p class="image-item">Likes <span class="image-caption">${g}</span></p>
        <p class="image-item">Views <span class="image-caption">${u}</span></p>
        <p class="image-item">Comments <span class="image-caption">${f}</span></p>
        <p class="image-item">Downloads <span class="image-caption">${h}</span></p>
  </figcaption>
  </figure>
</a>`}function $(e){return e.map(q).join("")}function E(e){if(e.length===0){b.show({icon:"icon-close",messageSize:"16px",backgroundColor:"red",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),r.style.display="none",i.innerHTML="";return}const o=$(e);try{i.insertAdjacentHTML("beforeend",o),d+=e.length}finally{a.style.display="none"}}async function v(){s++,a.style.display="block";try{const{data:e}=await L(l,s);E(e.hits);const o=Math.ceil(e.totalHits/15);w(o),y.refresh();const n=document.querySelectorAll(".gallery-link"),u=(n.length>0?n[0].offsetHeight:0)*2;window.scrollBy({behavior:"smooth",top:u})}catch(e){console.error("Error fetching more images:",e),S(`Error fetching more images: ${e}`)}finally{a.style.display="none"}}function S(e){b.show({message:e,backgroundColor:"#59A10D",progressBarColor:"#B5EA7C",icon:"icon-check"})}});
//# sourceMappingURL=commonHelpers.js.map
