import{S as $,a as v,i as h}from"./assets/vendor-da186403.js";(function(){const c=document.createElement("link").relList;if(c&&c.supports&&c.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function l(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=l(t);fetch(t.href,r)}})();document.addEventListener("DOMContentLoaded",function(){const d=document.querySelector(".search-form"),c=document.querySelector(".gallery"),l=document.querySelector(".search-btn"),s=document.querySelector(".loader"),t="gallery-link",r=document.querySelector(".load-more-btn");let n;l.disabled=!0;let p=1,g=null,u=0;d.elements.query.addEventListener("input",function(){g=this.value.trim(),l.disabled=g===""}),d.addEventListener("submit",async function(e){e.preventDefault();const o=e.target.elements.query.value.trim();if(o!=="")try{const a=await b(o,1);s.style.display="none",w(a.hits),l.disabled=!0,u=a.total,L(),n=new $(`.${t}`,{captionsData:"alt",captionDelay:250}),n.refresh(),n.on("show.simplelightbox")}catch(a){s.style.display="none",E(`Error fetching images: ${a}`)}finally{e.target.elements.query.value=""}});async function b(e,o=1){const a="https://pixabay.com/api/",y=`?${new URLSearchParams({key:"42137546-386b5be41212ccd429cab5a80",q:e,image_type:"photo",orientation:"horizontal",safeSearch:!0,per_page:15,page:o})}`,f=a+y;try{const i=await v.get(f);if(!i.data)throw new Error("No data returned from the API");return i.data}catch(i){throw new Error(`Error fetching images: ${i.message}`)}}function L(){if(u===0){r.style.display="none";return}Math.ceil(u/15)===p?(r.style.display="none",h.show({message:"We're sorry, but you've reached the end of search results.",color:"red",position:"topRight"})):r.style.display="block"}r.addEventListener("click",P);function S({webformatURL:e,largeImageURL:o,tags:a,likes:m,views:y,comments:f,downloads:i}){return`
  <a href="${o}" class="${t} id="gallery-link">
     <figure>
      <img src="${e}" alt="${a}" class="gallery-image">
      <figcaption class="gallery__figcaption">
        <p class="image-item">Likes <span class="image-caption">${m}</span></p>
        <p class="image-item">Views <span class="image-caption">${y}</span></p>
        <p class="image-item">Comments <span class="image-caption">${f}</span></p>
        <p class="image-item">Downloads <span class="image-caption">${i}</span></p>
  </figcaption>
  </figure>
</a>`}function q(e){return e.map(S).join("")}function w(e){if(e.length===0){h.show({icon:"icon-close",messageSize:"16px",backgroundColor:"red",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),r.style.display="none";return}const o=q(e);try{c.insertAdjacentHTML("beforeend",o),u+=e.length}finally{s.style.display="none"}}async function P(){p++,s.style.display="block";try{const e=await b(g,p);w(e.hits),L();const o=document.querySelectorAll(".gallery-link"),m=(o.length>0?o[0].offsetHeight:0)*2;window.scrollBy({behavior:"smooth",top:m})}catch(e){E(`Error fetching more images: ${e}`)}finally{s.style.display="none"}}function E(e){h.show({message:e,backgroundColor:"#59A10D",progressBarColor:"#B5EA7C",icon:"icon-check",...toastOptions})}});
//# sourceMappingURL=commonHelpers.js.map
